language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t gitznik/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true gitznik/react-test npm test

after_success:
  - docker build -t gitznik/multi-client ./client
  - docker build -t gitznik/multi-nginx ./nginx
  - docker build -t gitznik/multi-server ./server
  - docker build -t gitznik/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gitznik/multi-client
  - docker push gitznik/multi-nginx
  - docker push gitznik/multi-server
  - docker push gitznik/multi-worker
